### ISSUE TITLE
Classcast exception while getting layers

### ISSUE THREAD

**Issue by idar** [itext/itextpdf#17]
Using iText 5.5.9
While reading this pdf: [Failingpdf](https://www.dropbox.com/s/9vf34jr48voz3si/failing.pdf?dl=0)

`       final InputStream pdf = FileLoadUtil.getInputStreamForFileFromClasspath("failing.pdf");
        PdfReader reader = new PdfReader(pdf);
        PdfStamper stamper = new PdfStamper(reader, new ByteArrayOutputStream());
        stamper.getPdfLayers();`

I get this exception:

`java.lang.ClassCastException: com.itextpdf.text.pdf.PRIndirectReference cannot be cast to com.itextpdf.text.pdf.PdfArray

	at com.itextpdf.text.pdf.PdfStamperImp.addOrder(PdfStamperImp.java:1897)
	at com.itextpdf.text.pdf.PdfStamperImp.addOrder(PdfStamperImp.java:1877)
	at com.itextpdf.text.pdf.PdfStamperImp.addOrder(PdfStamperImp.java:1877)
	at com.itextpdf.text.pdf.PdfStamperImp.addOrder(PdfStamperImp.java:1877)
	at com.itextpdf.text.pdf.PdfStamperImp.readOCProperties(PdfStamperImp.java:1843)
	at com.itextpdf.text.pdf.PdfStamperImp.getPdfLayers(PdfStamperImp.java:1913)
	at com.itextpdf.text.pdf.PdfStamper.getPdfLayers(PdfStamper.java:815)
	at no.ks.svarut.forsendelsesfil.ForsendelsePdfLagerTest.filSomFeiler(ForsendelsePdfLagerTest.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)`

**Comment by amedee** [comment]
Hello, and thank you for using iText. 
If you have a support contract, please ask your question on the iText JIRA.
If you use the iText Community (AGPL) edition, please ask your question on StackOverflow and tag your question with iText: http://stackoverflow.com/questions/tagged/itext 

We use GitHub issues only for bug reports and pull requests.

For more information about our support options, see http://itextpdf.com/support
